name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/auto-update-route53

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.IMAGE_NAME }}:latest
          annotations: ${{ steps.meta.outputs.annotations }}
      - name: Dockerhub Readme
        # You may pin to the exact commit or the version.
        # uses: ms-jpq/sync-dockerhub-readme@e2991ea1ba48832e73555cdbd5b82f5a2e91ee9b
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          # Dockerhub username
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # path to readme markdown
          readme: /README.md
          # list of repositories to update (without username)
          repository: ${{ vars.DOCKERHUB_USERNAME }}/auto-update-route53
          
            
