name: Docker Image CI

on:
  push:
    branches: [ "pyrocro-patch-1" ]
  #pull_request:
  #  branches: [ "master" ]
  
env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/auto-update-route53

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:      
      - name: Docker Hub Description
        # You may pin to the exact commit or the version.
        # uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          # Docker Hub username
          username: ${{ vars.DOCKERHUB_USERNAME }}
          # Docker Hub password or Personal Access Token with read/write/delete scope
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          # Docker Hub repository in the format `<namespace>/<name>` Default: `github.repository`      
          #repository: # optional
          # Docker Hub repository short description
          #short-description: # optional
          # Path to the repository readme Default: `./README.md`      
          readme-filepath: './README.md' # optional '/home/runner/work/AutoUpdateRoute53/AutoUpdateRoute53/README.md'
          # Enables completion of relative URLs to absolute ones Default: `false`      
          #enable-url-completion: # optional
          # File extensions that will be treated as images Default: `bmp,gif,jpg,jpeg,png,svg,webp`      
          #image-extensions: # optional
          
          
            
